/**
 * Files of the active SD release generated by the service publisher:
 * compatibility.json (reviewed firmware identity), commands.json (reviewed
 * command catalog) and queries.json (reviewed data queries).
 *
 * In a build, every script lives in <release>/assets/, so the release root is
 * one level above this module. In development the Vite proxy exposes the
 * gateway's active release (see vite.config.ts).
 */
export interface Compatibility {
  schema: number
  api: number
  protocol_identity: string
  main_os_version: number
  profile_sha256: string
}

export interface CatalogRecord {
  name: string
  kind: 'read' | 'mutation'
  class: string
  payload: string
  reply: string | null
  silent_ok: boolean
  timeout_ms: number
  pacing_ms: number
  max_bytes: number
}

export interface CatalogRoute {
  name: string
  method: string
  path: string
  kind: 'read' | 'mutation'
  max_body_bytes: number
  /** Admitted header patterns (for capability checks such as favorites removal). */
  headers?: Record<string, string>
}

export interface CommandCatalog {
  api: number
  version: string
  profile_sha256: string
  catalog_sha256: string
  records: Record<string, CatalogRecord>
  http?: CatalogRoute[]
}

const PARENT = '..'

async function releaseRoot(): Promise<URL> {
  if (!import.meta.env.DEV) return new URL(PARENT + '/', import.meta.url)
  const index = await (await fetch('/__disc_active', { cache: 'no-store' })).text()
  const bundle = /\/releases\/([0-9a-f]{16})\//.exec(index)?.[1]
  if (!bundle) throw new Error('The gateway has no active release to develop against')
  return new URL(`/releases/${bundle}/`, location.href)
}

async function releaseJson<T>(name: string): Promise<T> {
  const response = await fetch(new URL(name, await releaseRoot()), { cache: 'no-store' })
  if (!response.ok) throw new Error(`${name}: HTTP ${response.status}`)
  return (await response.json()) as T
}

export const loadCompatibility = (): Promise<Compatibility> => releaseJson<Compatibility>('compatibility.json')
export const loadCommands = (): Promise<CommandCatalog> => releaseJson<CommandCatalog>('commands.json')

/** Whether the connected player matches the reviewed profile this release was built for. */
export function isCompatible(profile: Compatibility, handshake: string, socVersion: number | null): boolean {
  return (
    profile.schema === 1 &&
    profile.api === 1 &&
    /^[0-9a-f]{4}$/.test(profile.protocol_identity) &&
    Number.isInteger(profile.main_os_version) &&
    profile.main_os_version > 0 &&
    /^[0-9a-f]{64}$/.test(profile.profile_sha256) &&
    handshake === profile.protocol_identity &&
    socVersion === profile.main_os_version
  )
}
